API_URL = "http://127.0.0.1:8000/login"
LOGO_PATH = r"model\src\logo.png"
BG_LOGIN = r"model\src\LoginFundoVerde.png"
PROFILE = r"model\src\VectorProfile.png"
PASSWORD = r"model\src\VectorPassword.png"
EMAIL = r"model\src\VectorEmail.png"